site_name: 'SMT导航'
site_author: '销锋镝铸'
repo_name: 'SMT3'
repo_url: 'https://github.com/XiaofengdiZhu/SMT3'
use_directory_urls: false
site_dir: 'www'

theme:
  name: 'material'
  custom_dir: 'material'
  language: 'zh'
  static_templates:
    - '404.html'
  feature:
    tabs: true
  palette:
    primary: 'green'
    accent: 'green'
    language: 'zh'
    
extra:
  search:
    language: 'en, jp'
  social:
    - type: github-alt
      link: 'https://github.com/XiaofengdiZhu'

extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
 - 'cordova.js'
 - 'javascript/extra.js'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - qrcode:
      pixelsize: 6
      lightcolor: '#ffffff'
      darkcolor: '#000000'
      bordercolor: '#000000'

google_analytics:
  - 'UA-119895782-1'
  - 'auto'

pages:
  - 'SMT相关':
    - '简介': 'index.md'
    - '组规': 'about_SMT/SMT_rules.md'
    - '历史': 'about_SMT/SMT_history.md'
    - '组员': 'about_SMT/SMT_members.md'
  - '资源下载':
    - '导航版本更新&离线': 'download_resources/nav_update.md'
    - '资源下载整合': 'download_resources/resources.md'