site_name: 'SMT导航'
site_author: '销锋镝铸'
repo_name: 'SMT3'
repo_url: 'https://github.com/XiaofengdiZhu/SMT3'
use_directory_urls: false
site_dir: 'mkdocsOutput'

theme:
  name: 'material'
  custom_dir: 'material'
  language: 'zh'
  favicon: 'favicon.png'
  logo: 'saiming/web_logo.png'
  static_templates:
    - '404.html'
    - 'assets/no_cached/index.html'
    - 'assets/check_update/index.html'
  feature:
    tabs: true
  palette:
    primary: 'green'
    accent: 'green'
    language: 'zh'
    
extra:
  search:
    language: 'en, jp'
  social:
    - type: github-alt
      link: 'https://github.com/XiaofengdiZhu'

extra_css:
  - 'stylesheets/extra.css'
extra_javascript:
 - 'javascript/extra.js'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - qrcode:
      pixelsize: 6
      lightcolor: '#ffffff'
      darkcolor: '#000000'
      bordercolor: '#000000'

google_analytics:
  - 'UA-119895782-1'
  - 'auto'

pages:
  - '关于SMT':
    - '简介': 'index.md'
    - '编写人员': 'about_SMT/staff.md'
    - '组规': 'about_SMT/SMT_rules.md'
    - '历史': 'about_SMT/SMT_history.md'
    - '组员': 'about_SMT/SMT_members.md'
    - '导航更新&离线': 'about_SMT/nav_update.md'
  - 'MOD教程':
    - '序': 'tutorial/preface.md'
    - '资源下载整合': 'tutorial/resources.md'
    - 'Android基础教程': 'tutorial/android_tutorial.md'
    - 'Windows基础教程': 'tutorial/windows_tutorial.md'
    - 'Content解析': 'tutorial/content_tutorial.md'
    - 'BlocksData解析': 'tutorial/blocksdata_tutorial.md'
    - 'XML教程': 'tutorial/xml_tutorial.md'
    - 'Clothes解析': 'tutorial/clothes_tutorial.md'
    - 'CraftingRecipes解析': 'tutorial/craftingrecipes_tutorial.md'
    - 'Database解析': 'tutorial/database_tutorial.md'
    - '“源代码”教程': 'tutorial/source_code_tutorial.md'
    - '正则表达式教程': 'tutorial/regex_tutorial.md'
  - '例子':
    - '发布范例': 'other_tutorial/publication_example.md'